---
- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: dnf Update
  command: dnf -y update
  when: skip_dnf_update is not defined

- name: Basic packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - wget
      - bash-completion
      - python2-libselinux
      - gnome-tweak-tool
      - htop

- name: Bash Profile
  copy:
    src: ./../templates/etc/profile.d/zz_ec.sh
    dest: /etc/profile.d/zz_ec.sh

- name: Vimrc
  copy:
    src: ./../templates/etc/vimrc
    dest: /etc/vimrc

- name: Vim colour scheme
  copy:
    src: ./../templates/usr/share/vim/vimfiles/colors/deus.vim
    dest: /usr/share/vim/vimfiles/colors/deus.vim

- name: Locale
  copy:
    content: |
      LANG=en_GB.utf8
      export LANG
      LC_ALL=en_GB.UTF-8
      export LC_ALL
    dest: /etc/profile.d/zz_locale.sh

- name: Dont Send Locale over SSH
  replace:
    path: /etc/ssh/ssh_config.d/05-redhat.conf
    regexp: '^   SendEnv'
    replace: '#   SendEnv'

- name: Timezone
  command: timedatectl set-timezone Europe/London

- name: Passwordless Wheel Sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'

- name: Set hostname to match ansible hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: gsettings
  shell: |
    gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing "rgba"
    gsettings set org.gnome.settings-daemon.plugins.xsettings hinting "slight"

- name: Harden SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    regexp: "{{ item.regexp | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    validate: '/usr/sbin/sshd -T -f %s'
  with_items:
    - line: AllowUsers {{ users_name }} {{ ansible_ssh_user }}
    - line: Port {{ ssh_port }}
      regexp: "#Port"
    - line: AddressFamily inet
      regexp: "^#AddressFamily"
    - line: PermitRootLogin yes
      regexp: "^PermitRootLogin"
    - line: X11Forwarding no
      regexp: "^X11Forwarding"
    - line: UseDNS no
      regexp: "^#UseDNS"

- name: Update SE Linux for SSH Port
  shell: |
    semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
    systemctl restart sshd

- name: Ensure we are now using the updated SSH port
  set_fact:
    ansible_port: "{{ ssh_port }}"


