---
- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: dnf Update
  command: dnf -y update
  when: skip_dnf_update is not defined

- name: Basic packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - wget
      - bash-completion
      - gnome-tweak-tool
      - htop
      - gnote
      - terminator

- name: Fedora 30 Specific Packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python3-pexpect
      - python3-psutil
  when:
    - ansible_facts['distribution_major_version'] == "30"

- name: Bash Profile
  copy:
    src: ./../templates/etc/profile.d/zz_ec.sh
    dest: /etc/profile.d/zz_ec.sh

- name: Vimrc
  template:
    src: "{{ ec_fedora.vim.rc_path }}"
    dest: /etc/vimrc
  when: ec_fedora.vim.rc == true

- name: Vim colour scheme
  copy:
    src: "{{ ec_fedora.vim.colour_scheme_path }}"
    dest: /usr/share/vim/vimfiles/colors/deus.vim
  when: ec_fedora.vim.colour_scheme == true

- name: Locale
  copy:
    content: |
      LANG=en_GB.utf8
      export LANG
      LC_ALL=en_GB.UTF-8
      export LC_ALL
    dest: /etc/profile.d/zz_locale.sh

- name: Set ssh filename (Fedora 30)
  set_fact:
    ssh_config_file: /etc/ssh/ssh_config.d/05-redhat.conf
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version | int <= 30

- name: Set ssh filename (Fedora 30+)
  set_fact:
    ssh_config_file: /etc/ssh/ssh_config.d/50-redhat.conf
  when:
    - ansible_distribution == 'Fedora'
    - ansible_distribution_major_version | int > 30

- name: Dont Send Locale over SSH
  replace:
    path: "{{ ssh_config_file }}"
    regexp: '^[^#]+?SendEnv'
    replace: '#   SendEnv'

- name: Keep SSH Auth Sock when using Sudo
  copy:
    dest: /etc/sudoers.d/keep-auth-sock
    content: |
      Defaults    env_keep+=SSH_AUTH_SOCK

- name: Timezone
  command: timedatectl set-timezone Europe/London

- name: Passwordless Wheel Sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
    validate: '/usr/sbin/visudo -cf %s'

- name: Set hostname to match ansible hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: Harden SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "{{ item.line }}"
    regexp: "{{ item.regexp | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    validate: '/usr/sbin/sshd -T -f %s'
  with_items:
    - line: AllowUsers {{ users_name }} {{ ansible_ssh_user }}
    - line: AddressFamily inet
      regexp: "^#AddressFamily"
    - line: PermitRootLogin yes
      regexp: "^PermitRootLogin"
    - line: X11Forwarding no
      regexp: "^X11Forwarding"
    - line: UseDNS no
      regexp: "^#UseDNS"

- name: Update SSH Port
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "Port {{ ssh_port }}"
    regexp: "#Port"
    state: "{{ item.state | default('present') }}"
    validate: '/usr/sbin/sshd -T -f %s'
  when: ec_fedora.ssh.update_port == true

- name: Update SE Linux for SSH Port
  shell: |
    semanage port -a -t ssh_port_t -p tcp {{ ssh_port }}
    systemctl restart sshd

- name: Ensure we are now using the updated SSH port
  set_fact:
    ansible_port: "{{ ssh_port }}"
  when: ec_fedora.ssh.update_port == true

- name: Update DNS Resolution
  copy:
    dest: /etc/resolv.conf
    content: |
      # see https://www.dnsperf.com/#!dns-providers,Europe
      options timeout:1 attempts:1
      # cloudflare
      nameserver 1.1.1.1
      #OpenDNS
      nameserver 208.67.222.222
      nameserver 208.67.220.220
      #Google
      nameserver 8.8.8.8
      nameserver 8.8.4.4