---
- name: "Check required variables"
  fail: msg="Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{required_vars}}"

- name: dnf Update
  command: dnf -y update

- name: Basic packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - vim
      - wget
      - bash-completion
      - python2-libselinux


- name: Bash Profile
  template:
    src: etc/profile.d/zz_ec.sh
    dest: /etc/profile.d/zz_ec.sh

- name: Locale
  copy:
    content: |
      LANG=en_GB.utf8
      export LANG
      LC_ALL=en_GB.UTF-8
      export LC_ALL
    dest: /etc/profile.d/zz_locale.sh

- name: Timezone
  command: timedatectl set-timezone Europe/London

#- name: Passwordless Wheel Sudo
#  lineinfile:
#    path: /etc/sudoers
#    state: present
#    regexp: "^.+?%wheel"
#    line: "%wheel	ALL=(ALL)	NOPASSWD: ALL"
#    validate: '/usr/sbin/visudo -cf %s'

- name: Set hostname to match ansible hostname
  command: hostnamectl set-hostname "{{ inventory_hostname }}"

- name: gsettings
  shell: |
    gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing "rgba"
    gsettings set org.gnome.settings-daemon.plugins.xsettings hinting "slight"


